<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>Yandex.Tests</AssemblyName>
    <RootNamespace>Yandex.Tests</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Version>1.0</Version>
    <Company>Prokhor Ozornin &lt;prokhor.ozornin@yandex.ru&gt;</Company>
    <Authors>Prokhor Ozornin &lt;prokhor.ozornin@yandex.ru&gt;</Authors>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ProduceReferenceAssembly>False</ProduceReferenceAssembly>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <DocumentationFile>API.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="8.2.0" />
    <PackageReference Include="FluentAssertions.Json" Version="8.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="xunit" Version="2.9.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Yandex.Core\Yandex.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Catharsis.Commons">
      <HintPath>\\NAS\build\NET\Catharsis.Commons\net9.0\Catharsis.Commons.dll</HintPath>
    </Reference>
    <Reference Include="Catharsis.Extensions">
      <HintPath>\\NAS\build\NET\Catharsis.Extensions\net9.0\Catharsis.Extensions.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
